spring:
  datasource:
    url: jdbc:mysql://localhost:3306/relationTest
    username: root
    password: Pass1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: false